REAL_TICKERS = [
    "A","AAPL","ABBV","ABNB","ABT","ACGL","ACN","ADBE","ADI","ADM","ADP","ADSK",
    "AEE","AEP","AES","AFL","AIG","AIZ","AJG","AKAM","ALB","ALGN","ALL","ALLE",
    "AMAT","AMCR","AMD","AME","AMGN","AMP","AMT","AMZN","ANET","AON","AOS","APA",
    "APD","APH","APO","APTV","ARE","ATO","AVB","AVGO","AVY","AWK","AXON","AXP",
    "AZO","BA","BAC","BALL","BAX","BBY","BDX","BEN","BF.B","BG","BIIB","BK",
    "BKNG","BKR","BLDR","BLK","BMY","BR","BRK.B","BRO","BSX","BX","BXP","C","CAG",
    "CAH","CARR","CAT","CEG","CF","CHD","CHRW","CI","CINF","CL","CLX","CMCSA",
    "CME","CMG","CMI","CMS","CNC","CNP","COF","COO","COP","COR","COST","CPAY",
    "CPB","CPRT","CPT","CRM","CRWD","CSCO","CSGP","CSX","CTAS","CTRA","CTSH",
    "CTVA","CVS","CVX","CZR","D","DAL","DD","DE","DECK","DG","DGX","DHI","DHR",
    "DIS","DLR","DLTR","DOC","DOV","DOW","DPZ","DRI","DTE","DUK","DVA","DVN",
    "DXCM","EA","EBAY","ECL","ED","EFX","EG","EIX","EL","ELV","EMN","EMR","ENPH",
    "EOG","EPAM","EQIX","EQR","EQT","ERIE","ES","ESS","ETN","ETR","EVRG","EW",
    "EXC","EXE","EXPD","EXPE","EXR","F","FANG","FAST","FCX","FDS","FDX","FE",
    "FFIV","FI","FICO","FIS","FITB","FMC","FOX","FOXA","FRT","FSLR","FTNT","FTV",
    "GD","GDDY","GE","GEHC","GEN","GEV","GILD","GIS","GL","GLW","GM","GNRC","GOOG",
    "GOOGL","GPC","GPN","GRMN","GS","GWW","HCA","HD","HES","HIG","HII","HLT",
    "HOLX","HON","HPE","HPQ","HRL","HSIC","HST","HSY","HUBB","HUM","HWM","IBM",
    "ICE","IDXX","IEX","IFF","INCY","INTC","INTU","INVH","IP","IPG","IQV","IR",
    "IRM","ISRG","IT","ITW","J","JBHT","JBL","JCI","JKHY","JNJ","JNPR","JPM",
    "K","KDP","KEY","KEYS","KHC","KIM","KKR","KLAC","KMB","KMI","KMX","KO","KR",
    "KVUE","L","LDOS","LEN","LH","LHX","LII","LIN","LKQ","LLY","LMT","LNT","LOW",
    "LRCX","LULU","LUV","LYB","LYV","MA","MAA","MAR","MAS","MCD","MCHP","MCK",
    "MCW","MDLZ","MDT","MET","META","MGM","MHK","MKC","MKTX","MLM","MMC","MMM",
    "MNST","MO","MOH","MOS","MPC","MPWR","MRK","MRNA","MSCI","MSFT","MSI","MTB",
    "MTCH","MTD","MU","NCLH","NDAQ","NDSN","NEE","NEM","NFLX","NI","NKE","NOC",
    "NOW","NRG","NSC","NTAP","NTRS","NUE","NVDA","NVR","NWS","NWSA","NXPI","O",
    "ODFL","OKE","OMC","ON","ORCL","ORLY","OTIS","OXY","PANW","PAYC","PAYX","PCAR",
    "PCG","PEG","PEP","PFE","PFG","PG","PGR","PH","PHM","PKG","PLD","PLTR","PM",
    "PNC","PNR","PNW","PODD","POOL","PPG","PPL","PRU","PSA","PSX","PTC","PWR",
    "PYPL","QCOM","RCL","REG","REGN","RF","RJF","RL","RMD","ROK","ROL","ROP",
    "ROST","RSG","RTX","RVTY","SBAC","SBUX","SCHW","SHW","SJM","SLB","SMCI","SNA",
    "SNPS","SO","SOLV","SPGI","SRE","STE","STLD","STT","STX","STZ","SW","SWK",
    "SWKS","SYF","SYK","SYY","T","TAP","TDG","TDY","TECH","TER","TFC","TGT","TJX",
    "TMO","TMUS","TPL","TPR","TRGP","TRMB","TROW","TRV","TSCO","TSLA","TSN","TT",
    "TTWO","TXN","TXT","TYL","UHS","ULTA","UNH","UNP","UPS","URI","USB","V","VICI",
    "VLO","VLTO","VMC","VRSK","VRSN","VRTX","VST","VTR","VTRS","VZ","WAB","WAT",
    "WBD","WDC","WEC","WELL","WFC","WM","WMB","WMT","WRB","WST","WTW","WY","XEL",
    "XYL","YUM","ZBH","ZBRA","ZTS","DELL","ARM","SNAP","SOFI","RIVN","LCID","HOOD","COIN","MSTR",
    "CRWD","APP","VRT","FIX","SNDK","CIEN","TTD","SHOP","UBER","PLTR","RKLB","SOUN",
    "ASTS","HIMS","UPST","CVNA","RBLX","RDDT","PATH","AFRM","LITE","COHR","SATS",
    "TERN","MARA","RIOT","CLSK","IREN","OKLO","SMR","NNE","LUNR","TEM","GTLB",
    "ZS","NET","SNOW","DDOG","MDB","ESTC","AI","IONQ","PINS","SPOT","BABA","JD",
    "PDD","XOM","MS","HUT","BITB","SPCE","KTOS","DKNG","CHWY","SQ","MELI","ASML",
    "TEAM","WDAY","SE","BNTX","CELH","ELF","DUOL","SYM","RUM"
]


COMPANY_NAMES = {
    "A": "Agilent Technologies, Inc.",
    "AAPL": "Apple Inc.",
    "ABBV": "AbbVie Inc.",
    "ABNB": "Airbnb, Inc.",
    "ABT": "Abbott Laboratories",
    "ACGL": "Arch Capital Group Ltd.",
    "ACN": "Accenture plc",
    "ADBE": "Adobe Inc.",
    "ADI": "Analog Devices, Inc.",
    "ADM": "Archer-Daniels-Midland Company",
    "ADP": "Automatic Data Processing, Inc.",
    "ADSK": "Autodesk, Inc.",
    "AEE": "Ameren Corporation",
    "AEP": "American Electric Power Company, Inc.",
    "AES": "AES Corporation",
    "AFL": "Aflac Incorporated",
    "AIG": "American International Group, Inc.",
    "AIZ": "Assurant, Inc.",
    "AJG": "Arthur J. Gallagher & Co.",
    "AKAM": "Akamai Technologies, Inc.",
    "ALB": "Albemarle Corporation",
    "ALGN": "Align Technology, Inc.",
    "ALL": "The Allstate Corporation",
    "ALLE": "Allegion plc",
    "AMAT": "Applied Materials, Inc.",
    "AMCR": "Amcor plc",
    "AMD": "Advanced Micro Devices, Inc.",
    "AME": "AMETEK, Inc.",
    "AMGN": "Amgen Inc.",
    "AMP": "Ameriprise Financial, Inc.",
    "AMT": "American Tower Corporation",
    "AMZN": "Amazon.com, Inc.",
    "ANET": "Arista Networks, Inc.",
    "AON": "Aon plc",
    "AOS": "A. O. Smith Corporation",
    "APA": "APA Corporation",
    "APD": "Air Products and Chemicals, Inc.",
    "APH": "Amphenol Corporation",
    "APO": "Apollo Global Management, Inc.",
    "APTV": "Aptiv PLC",
    "ARE": "Alexandria Real Estate Equities, Inc.",
    "ATO": "Atmos Energy Corporation",
    "AVB": "AvalonBay Communities, Inc.",
    "AVGO": "Broadcom Inc.",
    "AVY": "Avery Dennison Corporation",
    "AWK": "American Water Works Company, Inc.",
    "AXON": "Axon Enterprise, Inc.",
    "AXP": "American Express Company",
    "AZO": "AutoZone, Inc.",
    "BA": "The Boeing Company",
    "BAC": "Bank of America Corporation",
    "BALL": "Ball Corporation",
    "BAX": "Baxter International Inc.",
    "BBY": "Best Buy Co., Inc.",
    "BDX": "Becton, Dickinson and Company",
    "BEN": "Franklin Resources, Inc.",
    "BF.B": "Brown-Forman Corporation",
    "BG": "Bunge Global SA",
    "BIIB": "Biogen Inc.",
    "BK": "The Bank of New York Mellon Corporation",
    "BKNG": "Booking Holdings Inc.",
    "BKR": "Baker Hughes Company",
    "BLDR": "Builders FirstSource, Inc.",
    "BLK": "BlackRock, Inc.",
    "BMY": "Bristol-Myers Squibb Company",
    "BR": "Broadridge Financial Solutions, Inc.",
    "BRK.B": "Berkshire Hathaway Inc.",
    "BRO": "Brown & Brown, Inc.",
    "BSX": "Boston Scientific Corporation",
    "BX": "Blackstone Inc.",
    "BXP": "Boston Properties, Inc.",
    "C": "Citigroup Inc.",
    "CAG": "Conagra Brands, Inc.",
    "CAH": "Cardinal Health, Inc.",
    "CARR": "Carrier Global Corporation",
    "CAT": "Caterpillar Inc.",
    "CEG": "Constellation Energy Corporation",
    "CF": "CF Industries Holdings, Inc.",
    "CHD": "Church & Dwight Co., Inc.",
    "CHRW": "C.H. Robinson Worldwide, Inc.",
    "CI": "The Cigna Group",
    "CINF": "Cincinnati Financial Corporation",
    "CL": "Colgate-Palmolive Company",
    "CLX": "The Clorox Company",
    "CMCSA": "Comcast Corporation",
    "CME": "CME Group Inc.",
    "CMG": "Chipotle Mexican Grill, Inc.",
    "CMI": "Cummins Inc.",
    "CMS": "CMS Energy Corporation",
    "CNC": "Centene Corporation",
    "CNP": "CenterPoint Energy, Inc.",
    "COF": "Capital One Financial Corporation",
    "COO": "The Cooper Companies, Inc.",
    "COP": "ConocoPhillips",
    "COR": "CoreSite Realty Corporation",
    "COST": "Costco Wholesale Corporation",
    "CPAY": "Corpay, Inc.",
    "CPB": "Campbell Soup Company",
    "CPRT": "Copart, Inc.",
    "CPT": "Camden Property Trust",
    "CRM": "Salesforce, Inc.",
    "CRWD": "CrowdStrike Holdings, Inc.",
    "CSCO": "Cisco Systems, Inc.",
    "CSGP": "CoStar Group, Inc.",
    "CSX": "CSX Corporation",
    "CTAS": "Cintas Corporation",
    "CTRA": "Coterra Energy Inc.",
    "CTSH": "Cognizant Technology Solutions Corporation",
    "CTVA": "Corteva, Inc.",
    "CVS": "CVS Health Corporation",
    "CVX": "Chevron Corporation",
    "CZR": "Caesars Entertainment, Inc.",
    "D": "Dominion Energy, Inc.",
    "DAL": "Delta Air Lines, Inc.",
    "DD": "DuPont de Nemours, Inc.",
    "DE": "Deere & Company",
    "DECK": "Deckers Outdoor Corporation",
    "DG": "Dollar General Corporation",
    "DGX": "Quest Diagnostics Incorporated",
    "DHI": "D.R. Horton, Inc.",
    "DHR": "Danaher Corporation",
    "DIS": "The Walt Disney Company",
    "DLR": "Digital Realty Trust, Inc.",
    "DLTR": "Dollar Tree, Inc.",
    "DOC": "Healthpeak Properties, Inc.",
    "DOV": "Dover Corporation",
    "DOW": "Dow Inc.",
    "DPZ": "Domino's Pizza, Inc.",
    "DRI": "Darden Restaurants, Inc.",
    "DTE": "DTE Energy Company",
    "DUK": "Duke Energy Corporation",
    "DVA": "DaVita Inc.",
    "DVN": "Devon Energy Corporation",
    "DXCM": "DexCom, Inc.",
    "EA": "Electronic Arts Inc.",
    "EBAY": "eBay Inc.",
    "ECL": "Ecolab Inc.",
    "ED": "Consolidated Edison, Inc.",
    "EFX": "Equifax Inc.",
    "EG": "Evergy, Inc.",
    "EIX": "Edison International",
    "EL": "The Estée Lauder Companies Inc.",
    "ELV": "Elevance Health, Inc.",
    "EMN": "Eastman Chemical Company",
    "EMR": "Emerson Electric Co.",
    "ENPH": "Enphase Energy, Inc.",
    "EOG": "EOG Resources, Inc.",
    "EPAM": "EPAM Systems, Inc.",
    "EQIX": "Equinix, Inc.",
    "EQR": "Equity Residential",
    "EQT": "EQT Corporation",
    "ERIE": "Erie Indemnity Company",
    "ES": "Eversource Energy",
    "ESS": "Essex Property Trust, Inc.",
    "ETN": "Eaton Corporation plc",
    "ETR": "Entergy Corporation",
    "EVRG": "Evergy, Inc.",
    "EW": "Edwards Lifesciences Corporation",
    "EXC": "Exelon Corporation",
    "EXE": "Exe Technologies Inc.",   # Note: Rare ticker, may need verification
    "EXPD": "Expeditors International of Washington, Inc.",
    "EXPE": "Expedia Group, Inc.",
    "EXR": "Extra Space Storage Inc.",
    "F": "Ford Motor Company",
    "FANG": "Diamondback Energy, Inc.",
    "FAST": "Fastenal Company",
    "FCX": "Freeport-McMoRan Inc.",
    "FDS": "FactSet Research Systems Inc.",
    "FDX": "FedEx Corporation",
    "FE": "FirstEnergy Corp.",
    "FFIV": "F5, Inc.",
    "FI": "Fiserv, Inc.",
    "FICO": "Fair Isaac Corporation",
    "FIS": "Fidelity National Information Services, Inc.",
    "FITB": "Fifth Third Bancorp",
    "FMC": "FMC Corporation",
    "FOX": "Fox Corporation",
    "FOXA": "Fox Corporation",
    "FRT": "Federal Realty Investment Trust",
    "FSLR": "First Solar, Inc.",
    "FTNT": "Fortinet, Inc.",
    "FTV": "Fortive Corporation",
    "GD": "General Dynamics Corporation",
    "GDDY": "GoDaddy Inc.",
    "GE": "General Electric Company",
    "GEHC": "GE HealthCare Technologies Inc.",
    "GEN": "Gen Digital Inc.",
    "GEV": "GE Vernova Inc.",
    "GILD": "Gilead Sciences, Inc.",
    "GIS": "General Mills, Inc.",
    "GL": "Globe Life Inc.",
    "GLW": "Corning Incorporated",
    "GM": "General Motors Company",
    "GNRC": "Generac Holdings Inc.",
    "GOOG": "Alphabet Inc.",
    "GOOGL": "Alphabet Inc.",
    "GPC": "Genuine Parts Company",
    "GPN": "Global Payments Inc.",
    "GRMN": "Garmin Ltd.",
    "GS": "The Goldman Sachs Group, Inc.",
    "GWW": "W.W. Grainger, Inc.",
    "HCA": "HCA Healthcare, Inc.",
    "HD": "The Home Depot, Inc.",
    "HES": "Hess Corporation",
    "HIG": "The Hartford Financial Services Group, Inc.",
    "HII": "Huntington Ingalls Industries, Inc.",
    "HLT": "Hilton Worldwide Holdings Inc.",
    "HOLX": "Hologic, Inc.",
    "HON": "Honeywell International Inc.",
    "HPE": "Hewlett Packard Enterprise Company",
    "HPQ": "HP Inc.",
    "HRL": "Hormel Foods Corporation",
    "HSIC": "Henry Schein, Inc.",
    "HST": "Host Hotels & Resorts, Inc.",
    "HSY": "The Hershey Company",
    "HUBB": "Hubbell Incorporated",
    "HUM": "Humana Inc.",
    "HWM": "Howmet Aerospace Inc.",
    "IBM": "International Business Machines Corporation",
    "ICE": "Intercontinental Exchange, Inc.",
    "IDXX": "IDEXX Laboratories, Inc.",
    "IEX": "IDEX Corporation",
    "IFF": "International Flavors & Fragrances Inc.",
    "INCY": "Incyte Corporation",
    "INTC": "Intel Corporation",
    "INTU": "Intuit Inc.",
    "INVH": "Invitation Homes Inc.",
    "IP": "International Paper Company",
    "IPG": "The Interpublic Group of Companies, Inc.",
    "IQV": "IQVIA Holdings Inc.",
    "IR": "Ingersoll Rand Inc.",
    "IRM": "Iron Mountain Incorporated",
    "ISRG": "Intuitive Surgical, Inc.",
    "IT": "Gartner, Inc.",
    "ITW": "Illinois Tool Works Inc.",
    "J": "Jacobs Solutions Inc.",
    "JBHT": "J.B. Hunt Transport Services, Inc.",
    "JBL": "Jabil Inc.",
    "JCI": "Johnson Controls International plc",
    "JKHY": "Jack Henry & Associates, Inc.",
    "JNJ": "Johnson & Johnson",
    "JNPR": "Juniper Networks, Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "K": "Kellanova",
    "KDP": "Keurig Dr Pepper Inc.",
    "KEY": "KeyCorp",
    "KEYS": "Keysight Technologies, Inc.",
    "KHC": "The Kraft Heinz Company",
    "KIM": "Kimco Realty Corporation",
    "KKR": "KKR & Co. Inc.",
    "KLAC": "KLA Corporation",
    "KMB": "Kimberly-Clark Corporation",
    "KMI": "Kinder Morgan, Inc.",
    "KMX": "CarMax, Inc.",
    "KO": "The Coca-Cola Company",
    "KR": "The Kroger Co.",
    "KVUE": "Kenvue Inc.",
    "L": "Loews Corporation",
    "LDOS": "Leidos Holdings, Inc.",
    "LEN": "Lennar Corporation",
    "LH": "Laboratory Corporation of America Holdings",
    "LHX": "L3Harris Technologies, Inc.",
    "LII": "Lennox International Inc.",
    "LIN": "Linde plc",
    "LKQ": "LKQ Corporation",
    "LLY": "Eli Lilly and Company",
    "LMT": "Lockheed Martin Corporation",
    "LNT": "Alliant Energy Corporation",
    "LOW": "Lowe's Companies, Inc.",
    "LRCX": "Lam Research Corporation",
    "LULU": "Lululemon Athletica Inc.",
    "LUV": "Southwest Airlines Co.",
    "LYB": "LyondellBasell Industries N.V.",
    "LYV": "Live Nation Entertainment, Inc.",
    "MA": "Mastercard Incorporated",
    "MAA": "Mid-America Apartment Communities, Inc.",
    "MAR": "Marriott International, Inc.",
    "MAS": "Masco Corporation",
    "MCD": "McDonald's Corporation",
    "MCHP": "Microchip Technology Incorporated",
    "MCK": "McKesson Corporation",
    "MCW": "Mister Car Wash, Inc.",
    "MDLZ": "Mondelez International, Inc.",
    "MDT": "Medtronic plc",
    "MET": "MetLife, Inc.",
    "META": "Meta Platforms, Inc.",
    "MGM": "MGM Resorts International",
    "MHK": "Mohawk Industries, Inc.",
    "MKC": "McCormick & Company, Incorporated",
    "MKTX": "MarketAxess Holdings Inc.",
    "MLM": "Martin Marietta Materials, Inc.",
    "MMC": "Marsh & McLennan Companies, Inc.",
    "MMM": "3M Company",
    "MNST": "Monster Beverage Corporation",
    "MO": "Altria Group, Inc.",
    "MOH": "Molina Healthcare, Inc.",
    "MOS": "The Mosaic Company",
    "MPC": "Marathon Petroleum Corporation",
    "MPWR": "Monolithic Power Systems, Inc.",
    "MRK": "Merck & Co., Inc.",
    "MRNA": "Moderna, Inc.",
    "MSCI": "MSCI Inc.",
    "MSFT": "Microsoft Corporation",
    "MSI": "Motorola Solutions, Inc.",
    "MTB": "M&T Bank Corporation",
    "MTCH": "Match Group, Inc.",
    "MTD": "Mettler-Toledo International Inc.",
    "MU": "Micron Technology, Inc.",
    "NCLH": "Norwegian Cruise Line Holdings Ltd.",
    "NDAQ": "Nasdaq, Inc.",
    "NDSN": "Nordson Corporation",
    "NEE": "NextEra Energy, Inc.",
    "NEM": "Newmont Corporation",
    "NFLX": "Netflix, Inc.",
    "NI": "NiSource Inc.",
    "NKE": "NIKE, Inc.",
    "NOC": "Northrop Grumman Corporation",
    "NOW": "ServiceNow, Inc.",
    "NRG": "NRG Energy, Inc.",
    "NSC": "Norfolk Southern Corporation",
    "NTAP": "NetApp, Inc.",
    "NTRS": "Northern Trust Corporation",
    "NUE": "Nucor Corporation",
    "NVDA": "NVIDIA Corporation",
    "NVR": "NVR, Inc.",
    "NWS": "News Corporation",
    "NWSA": "News Corporation",
    "NXPI": "NXP Semiconductors N.V.",
    "O": "Realty Income Corporation",
    "ODFL": "Old Dominion Freight Line, Inc.",
    "OKE": "ONEOK, Inc.",
    "OMC": "Omnicom Group Inc.",
    "ON": "ON Semiconductor Corporation",
    "ORCL": "Oracle Corporation",
    "ORLY": "O'Reilly Automotive, Inc.",
    "OTIS": "Otis Worldwide Corporation",
    "OXY": "Occidental Petroleum Corporation",
    "PANW": "Palo Alto Networks, Inc.",
    "PAYC": "Paycom Software, Inc.",
    "PAYX": "Paychex, Inc.",
    "PCAR": "PACCAR Inc.",
    "PCG": "PG&E Corporation",
    "PEG": "Public Service Enterprise Group Incorporated",
    "PEP": "PepsiCo, Inc.",
    "PFE": "Pfizer Inc.",
    "PFG": "Principal Financial Group, Inc.",
    "PG": "The Procter & Gamble Company",
    "PGR": "The Progressive Corporation",
    "PH": "Parker-Hannifin Corporation",
    "PHM": "PulteGroup, Inc.",
    "PKG": "Packaging Corporation of America",
    "PLD": "Prologis, Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "PM": "Philip Morris International Inc.",
    "PNC": "The PNC Financial Services Group, Inc.",
    "PNR": "Pentair plc",
    "PNW": "Pinnacle West Capital Corporation",
    "PODD": "Insulet Corporation",
    "POOL": "Pool Corporation",
    "PPG": "PPG Industries, Inc.",
    "PPL": "PPL Corporation",
    "PRU": "Prudential Financial, Inc.",
    "PSA": "Public Storage",
    "PSX": "Phillips 66",
    "PTC": "PTC Inc.",
    "PWR": "Quanta Services, Inc.",
    "PYPL": "PayPal Holdings, Inc.",
    "QCOM": "QUALCOMM Incorporated",
    "RCL": "Royal Caribbean Cruises Ltd.",
    "REG": "Regency Centers Corporation",
    "REGN": "Regeneron Pharmaceuticals, Inc.",
    "RF": "Regions Financial Corporation",
    "RJF": "Raymond James Financial, Inc.",
    "RL": "Ralph Lauren Corporation",
    "RMD": "ResMed Inc.",
    "ROK": "Rockwell Automation, Inc.",
    "ROL": "Rollins, Inc.",
    "ROP": "Roper Technologies, Inc.",
    "ROST": "Ross Stores, Inc.",
    "RSG": "Republic Services, Inc.",
    "RTX": "RTX Corporation",
    "RVTY": "Revvity, Inc.",
    "SBAC": "SBA Communications Corporation",
    "SBUX": "Starbucks Corporation",
    "SCHW": "The Charles Schwab Corporation",
    "SHW": "The Sherwin-Williams Company",
    "SJM": "The J. M. Smucker Company",
    "SLB": "Schlumberger Limited",
    "SMCI": "Super Micro Computer, Inc.",
    "SNA": "Snap-on Incorporated",
    "SNPS": "Synopsys, Inc.",
    "SO": "The Southern Company",
    "SOLV": "Solventum Corporation",
    "SPGI": "S&P Global Inc.",
    "SRE": "Sempra",
    "STE": "STERIS plc",
    "STLD": "Steel Dynamics, Inc.",
    "STT": "State Street Corporation",
    "STX": "Seagate Technology Holdings plc",
    "STZ": "Constellation Brands, Inc.",
    "SW": "Smurfit Westrock plc",
    "SWK": "Stanley Black & Decker, Inc.",
    "SWKS": "Skyworks Solutions, Inc.",
    "SYF": "Synchrony Financial",
    "SYK": "Stryker Corporation",
    "SYY": "Sysco Corporation",
    "T": "AT&T Inc.",
    "TAP": "Molson Coors Beverage Company",
    "TDG": "TransDigm Group Incorporated",
    "TDY": "Teledyne Technologies Incorporated",
    "TECH": "Bio-Techne Corporation",
    "TER": "Teradyne, Inc.",
    "TFC": "Truist Financial Corporation",
    "TGT": "Target Corporation",
    "TJX": "The TJX Companies, Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "TMUS": "T-Mobile US, Inc.",
    "TPL": "Texas Pacific Land Corporation",
    "TPR": "Tapestry, Inc.",
    "TRGP": "Targa Resources Corp.",
    "TRMB": "Trimble Inc.",
    "TROW": "T. Rowe Price Group, Inc.",
    "TRV": "The Travelers Companies, Inc.",
    "TSCO": "Tractor Supply Company",
    "TSLA": "Tesla, Inc.",
    "TSN": "Tyson Foods, Inc.",
    "TT": "Trane Technologies plc",
    "TTWO": "Take-Two Interactive Software, Inc.",
    "TXN": "Texas Instruments Incorporated",
    "TXT": "Textron Inc.",
    "TYL": "Tyler Technologies, Inc.",
    "UHS": "Universal Health Services, Inc.",
    "ULTA": "Ulta Beauty, Inc.",
    "UNH": "UnitedHealth Group Incorporated",
    "UNP": "Union Pacific Corporation",
    "UPS": "United Parcel Service, Inc.",
    "URI": "United Rentals, Inc.",
    "USB": "U.S. Bancorp",
    "V": "Visa Inc.",
    "VICI": "VICI Properties Inc.",
    "VLO": "Valero Energy Corporation",
    "VLTO": "Veralto Corporation",
    "VMC": "Vulcan Materials Company",
    "VRSK": "Verisk Analytics, Inc.",
    "VRSN": "VeriSign, Inc.",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "VST": "Vistra Corp.",
    "VTR": "Ventas, Inc.",
    "VTRS": "Viatris Inc.",
    "VZ": "Verizon Communications Inc.",
    "WAB": "Westinghouse Air Brake Technologies Corporation",
    "WAT": "Waters Corporation",
    "WBD": "Warner Bros. Discovery, Inc.",
    "WDC": "Western Digital Corporation",
    "WEC": "WEC Energy Group, Inc.",
    "WELL": "Welltower Inc.",
    "WFC": "Wells Fargo & Company",
    "WM": "Waste Management, Inc.",
    "WMB": "The Williams Companies, Inc.",
    "WMT": "Walmart Inc.",
    "WRB": "W. R. Berkley Corporation",
    "WST": "West Pharmaceutical Services, Inc.",
    "WTW": "Willis Towers Watson Public Limited Company",
    "WY": "Weyerhaeuser Company",
    "XEL": "Xcel Energy Inc.",
    "XYL": "Xylem Inc.",
    "YUM": "Yum! Brands, Inc.",
    "ZBH": "Zimmer Biomet Holdings, Inc.",
    "ZBRA": "Zebra Technologies Corporation",
    "ZTS": "Zoetis Inc.",
    "DELL": "Dell Technologies Inc.",
    "ARM": "Arm Holdings plc",
    "SNAP": "Snap Inc.",
    "SOFI": "SoFi Technologies, Inc.",
    "RIVN": "Rivian Automotive, Inc.",
    "LCID": "Lucid Group, Inc.",
    "HOOD": "Robinhood Markets, Inc.",
    "COIN": "Coinbase Global, Inc.",
    "MSTR": "MicroStrategy Incorporated",
    "CRWD": "CrowdStrike Holdings, Inc.",
    "APP": "AppLovin Corporation",
    "VRT": "Vertiv Holdings Co",
    "FIX": "Comfort Systems USA, Inc.",
    "CIEN": "Ciena Corporation",
    "TTD": "The Trade Desk, Inc.",
    "SHOP": "Shopify Inc.",
    "UBER": "Uber Technologies, Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "RKLB": "Rocket Lab USA, Inc.",
    "SOUN": "SoundHound AI, Inc.",
    "ASTS": "AST SpaceMobile, Inc.",
    "HIMS": "Hims & Hers Health, Inc.",
    "UPST": "Upstart Holdings, Inc.",
    "CVNA": "Carvana Co.",
    "RBLX": "Roblox Corporation",
    "RDDT": "Reddit, Inc.",
    "PATH": "UiPath Inc.",
    "AFRM": "Affirm Holdings, Inc.",
    "LITE": "Lumentum Holdings Inc.",
    "COHR": "Coherent Corp.",
    "SATS": "EchoStar Corporation",
    "TERN": "Terns Pharmaceuticals, Inc.",
    "MARA": "MARA Holdings, Inc.",
    "RIOT": "Riot Platforms, Inc.",
    "CLSK": "CleanSpark, Inc.",
    "IREN": "Iris Energy Limited",
    "OKLO": "Oklo Inc.",
    "SMR": "NuScale Power Corporation",
    "NNE": "Nano Nuclear Energy Inc.",
    "LUNR": "Intuitive Machines, Inc.",
    "TEM": "Tempus AI, Inc.",
    "GTLB": "GitLab Inc.",
    "ZS": "Zscaler, Inc.",
    "NET": "Cloudflare, Inc.",
    "SNOW": "Snowflake Inc.",
    "DDOG": "Datadog, Inc.",
    "MDB": "MongoDB, Inc.",
    "ESTC": "Elastic N.V.",
    "AI": "C3.ai, Inc.",
    "IONQ": "IonQ, Inc.",
    "PINS": "Pinterest, Inc.",
    "SPOT": "Spotify Technology S.A.",
    "BABA": "Alibaba Group Holding Limited",
    "JD": "JD.com, Inc.",
    "PDD": "PDD Holdings Inc.",
    "MS": "Morgan Stanley",
    "HUT": "Hut 8 Corp.",
    "BITB": "Bitwise Bitcoin ETF",   # ETF
    "SPCE": "Virgin Galactic Holdings, Inc.",
    "KTOS": "Kratos Defense & Security Solutions, Inc.",
    "DKNG": "DraftKings Inc.",
    "CHWY": "Chewy, Inc.",
    "SQ": "Block, Inc.",
    "MELI": "MercadoLibre, Inc.",
    "ASML": "ASML Holding N.V.",
    "TEAM": "Atlassian Corporation",
    "WDAY": "Workday, Inc.",
    "SE": "Sea Limited",
    "BNTX": "BioNTech SE",
    "CELH": "Celsius Holdings, Inc.",
    "ELF": "e.l.f. Beauty, Inc.",
    "DUOL": "Duolingo, Inc.",
    "SYM": "Symbotic Inc.",
    "RUM": "Rumble Inc."
}

# ---------------------------------------------------------
# 3) HELPER: GET COMPANY NAME
# ---------------------------------------------------------
def get_company_name(symbol: str) -> str:
    """
    Return a friendly company name for a ticker symbol.

    - Looks up `symbol` (case-insensitive) in TICKER_NAME_MAP.
    - Falls back to the upper-cased symbol if not found.
    """
    if not symbol:
        return ""

    sym = str(symbol).upper().strip()
    return COMPANY_NAMES.get(sym, sym)